### ISSUE TITLE
Error in rule chunk_chromosomes

### ISSUE THREAD

**Issue by jiangzy26** [nspope/singer-snakemake#2]
Hi, I am trying the snakemake with your example files , but I got the Error, could you share your help? Thanks

Config file config/example_config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 20
Rules claiming more threads will be scaled down.
Job stats:
job                       count    min threads    max threads
----------------------  -------  -------------  -------------
all                           1              1              1
chunk_chromosomes             1              1              1
coalescence_rates           100              1              1
diagnostics                   1              1              1
merge_chunks                100              1              1
plot_coalescence_rates        1              1              1
tree_statistics             100              1              1
total                       304              1              1

Select jobs to execute...

[Sun Sep 29 14:43:36 2024]
checkpoint chunk_chromosomes:
    input: example/example.vcf.gz
    output: results/example/example.vcf, results/example/plots/site_density.png, results/example/chunks, results/example/example.vcf.stats.p, results/example/example.adjusted_mu.p, results/example/example.vcf.samples.p
    log: results/example/example.log
    jobid: 1
    wildcards: chrom=example
    resources: tmpdir=/tmp
Downstream jobs will be updated after completion.

/data2/nt/sample/result/24-ARG/my-singer-run/workflow/scripts/chunk_chromosomes.py:162: RuntimeWarning: invalid value encountered in true_divide
  logfile.write(f"{tag()} Skipping {np.sum(~filter)} (of {filter.size}) chunks with too much missing data\n")
Traceback (most recent call last):
  File "/data2/nt/sample/result/24-ARG/my-singer-run/.snakemake/scripts/tmphc5dlw9s.chunk_chromosomes.py", line 187, in <module>
    vcf_prefix = snakemake.output.vcf.removesuffix(".vcf")
AttributeError: 'str' object has no attribute 'removesuffix'
[Sun Sep 29 14:43:37 2024]
Error in rule chunk_chromosomes:
    jobid: 1
    output: results/example/example.vcf, results/example/plots/site_density.png, results/example/chunks, results/example/example.vcf.stats.p, results/example/example.adjusted_mu.p, results/example/example.vcf.samples.p
    log: results/example/example.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 88 of /data2/nt/sample/result/24-ARG/my-singer-run/workflow/Snakefile:
Command 'set -euo pipefail;  /data2/software-use/anaconda3/envs/snakemake/bin/python3.7 /data2/nt/sample/result/24-ARG/my-singer-run/.snakemake/scripts/tmphc5dlw9s.chunk_chromosomes.py' returned non-zero exit status 1.
  File "/data2/nt/sample/result/24-ARG/my-singer-run/workflow/Snakefile", line 88, in __rule_chunk_chromosomes
  File "/data2/software-use/anaconda3/envs/snakemake/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Removing output files of failed job chunk_chromosomes since they might be corrupted:
results/example/plots/site_density.png, results/example/chunks
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data2/nt/sample/result/24-ARG/my-singer-run/.snakemake/log/2024-09-29T144334.947061.snakemak

**Comment by nspope** [comment]
You need Python version >= 3.9 for `"string".removesuffix(...)` to be available. If you're restricted to older Python versions, then clone the repo, and change
https://github.com/nspope/singer-snakemake/blob/50c57def9531eec651084ed05fd689d18fa5bafd/workflow/scripts/chunk_chromosomes.py#L183
to
```python
vcf_prefix = snakemake.output.vcf[:-4]
```
